### PR TITLE
Big rewrite

### PR DESCRIPTION
**Pull request by Hipska**
This is a WIP to add the following:

- [x] Support for metrics by tag
- [x] Single request for IN & OUT
- [x] Clean up the code and add comments/PHPDoc

Feel free to comment or add suggestions.

### CODE REVIEW

**Review by howardjones — COMMENTED** [review]
Since this is an actual error, it should probably be wm_warn() too. Those are the only ones that get logged if not in debug mode. (that's 
ebb37d6 - I thought github would attach this comment to that, sorry)

**Comment by Hipska** [comment]
@howardjones I don't fully agree on that, There could indeed be also a `wm_warn` message, but this message more looks like an actual debug message.

**Comment by howardjones** [comment]
Yes, you're right. In Init() you wouldn't want that every time if the plugin isn't in use. And you'd get the more generic `"ProcessTargets: %s, target: %s was recognised as a valid TARGET by a plugin that is unable to run (%s) [WMWARN07]\n"` already.

**Comment by Hipska** [comment]
Documentation added, please review @alexforrow. Will also add more advanced examples.

What do you think about also adding a `graphite_step` hint to set on the map or link by using `SET`. With that, it will be possible to finetune the `from` parameter.

**Review by alexforrow — APPROVED** [review]
This looks like a great improvement, however I don't have an environment set up to test. I'll merge this, but I wonder if it would be best for someone else to take ownership?

**Comment by Hipska** [comment]
Thanks, You can transfer it to me, and I will then transfer it to our organisation.

See https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by Hipska** [comment]
Hi @alexforrow, you need any more help on this?

**Comment by alexforrow** [comment]
I'm going to hold on to it for the time being, but if it becomes a problem I'll transfer.

**Pull request merged**
